### ISSUE TITLE
Builds are not transactional

### ISSUE THREAD

**Issue by andreypopp** [jordwalke/esy#18]
We should build in temp dir and `mv` to the esy's store when build is finished.

**Comment by kennetpostigo** [comment]
Hey @andreypopp , I want to help out.  Did you have any specific way you wanted to implement this?

**Comment by jordwalke** [comment]
@kennetpostigo You should start by looking at how esy sets up a place for packages to dump their out-of-source artifacts into `~/.esy/store`. Right now, all the opam converted packages don't respect that environment variable which performs out of source builds. We should come up with a solution that works in both cases - when a package respects that env var, and for packages that don't.

(Note, there's also an "install" directory in `~/.esy/store`, and most opam packages respect that out-of-source install location).

**Comment by kennetpostigo** [comment]
okay, I'll keep that in mind

**Comment by jordwalke** [comment]
<deleted>

**Comment by jordwalke** [comment]
I had a long comment here, but deleted it because I realized that the task should be transactional for the *entire* operation including building of all packages and my comment only referred to individual package builds. That is, if you have a clean, correctly building project, and you try to add a dependency, and that new dependency causes a failure, you should be able to instantly revert back to the old state of the world (in fact, reverting should be the default). The broken environment/builds should exist somewhere so that you can inspect them.

**Comment by jordwalke** [comment]
However, if we really do pick our cache key strategy correctly, then it should always be okay to build/install a subset of the packages into the `~/.esy/store` even if half of them fail. `esy`'s job is then to simply construct the correct subset of all those builds that represents your environment. Could we have something like an `~/.esySuccessfulEnv` which records the last correctly building environment (including what the `package.json` was at the time, where the `node_module/x` symlinks pointed to etc, the last ejected makefile the correctly build, the last ejected makefile that constructs the correct environment for said build). Then when an `npm` package operation fails, (or when your source/package.json/deps/code don't build correctly) `esy` can record that fact in a little file like `~/.esyIAmFailing`, and then `esy` will know to automatically fall back to the last correctly building environment by using `~/.esyEnvironment` instead of recomputing the makefile/environment on the fly.

In fact, doesn't this also solve the performance issue of recomputing all the env vars every time you do `esy my Command`? If you record the last successful ejected environment/makefile, then you can just reuse it - not only in the event that you screw up your environment/package.json/deps/code, but in the event that you *don't change* your environment/package.json/deps/code!

**Comment by andreypopp** [comment]
Hi @kennetpostigo!

The main problem is the following line of code https://github.com/jordwalke/esy/blob/master/lib/esyBuildRuntime.sh#L76

It assumes that if an output directory exists — then the corresponding package was built, the problem is that if there was a failure during build we can end up with the output directory which is empty (or just in inconsistent state).

A usual way to fix that is to build into some temp directory and then `mv` (this command is transactional in most filesystems except few, NFS for example) the temp directory into the output directory. The problem with that approach is that most of the builds in esy won't be relocatable — that's you can't move build OCaml artefacts around the filesystem.

Instead I think we could change the notion of "when does the build of the package is finished" from having a directory to having some sort of `_esy_build_finished` inside that directory.

The `esy-build-command` shell function in `esyBuildRuntime.sh` will do `touch $cur__install/_esy_build_finished` as its last command then (which is much much less likely to fail).

**Comment by jordwalke** [comment]
We should entertain the relocatability route. You mentioned ocaml and ocamlfind are not relocatable. For `ocaml`, we can require that byte code executables be invoked with `ocamlrun`, or that they are compiled with the `-custom` flag to make them self contained.

For `ocamlfind`, as you suggested we can make a patch for it. I'm asking around now to see how many cases we will run into. If it's many more than just `ocamlfind`, we may wish to maintain a patch on ocaml itself.

**Comment by kennetpostigo** [comment]
@andreypopp @jordwalke is this a good issue to make my first contribution to esy? Or do you recommend another one?
