### ISSUE TITLE
Push `opam` converter to Yunxing's npm-opam

### ISSUE THREAD

**Issue by jordwalke** [jordwalke/esy#33]
We can make `npm-opam` support both forms until `esy` becomes the standard.

https://github.com/yunxing/opam-npm

We should also consider having better documentation for how people can convert their own packages.

**Comment by andreypopp** [comment]
Currently at https://github.com/esy-ocaml/esy-opam

There are a couple of changes:
* We publish packages to a custom registry (rather than to GitHub repos and npm proxy packages within the package scope, like `@opam-alpha`).
* We specify concrete versions of OPAM packages which we need to convert (rather than the number of latest releases).

**Comment by jordwalke** [comment]
> We publish packages to a custom registry (rather than to GitHub repos and npm proxy packages within the package scope, like @opam-alpha).

Is there a reason why this is better than a git repo? I did not find a significant performance difference.


> We specify concrete versions of OPAM packages which we need to convert (rather than the number of latest releases).

Great!

**Comment by andreypopp** [comment]
Closing this as we integrated opam packages installation into `esy install` command.
