### ISSUE TITLE
Changing local dependency content doesn't invalidate esy cache

### ISSUE THREAD

**Issue by chenglou** [jordwalke/esy#59]
Installing the same local path makes esy thing it should retrieve content from cache, even when the content has changed.

Related: https://github.com/jordwalke/esy/issues/53#issuecomment-277408920

**Comment by jordwalke** [comment]
I've implemented and tested support for symlink dependencies and local dependencies. 
It currently rebuilds them every time you run `esy build`, but that might not be so bad since usually you would only be building your top level package rapidly. There's still more improvements left but there's tasks tracking them already.
In your case, don't forget to reinstall local `file:` dependencies, or they won't be updated and it will merely appear to be a stale cache. Only npm link will have a live link to dependencies. `file:` dependencies require you to rerun npm install.
