### ISSUE TITLE
Loose "esy <command>" sandboxing restrictions

### ISSUE THREAD

**Issue by andreypopp** [jordwalke/esy#7]
Currently `esy <command>` overrides `$PATH` env var so some of a user's commands stop working. We should make it not override `$PATH` but augment it instead.

**Comment by jordwalke** [comment]
We found that `esy vim` won't work because `esy` strips the environment so cleanly that the `$SHELL` env var is even reset, so Vim doesn't load anything useful.

**Comment by jordwalke** [comment]
I found another case where we really want *pure* behavior, and I thought I'd document it for future reference.

For [global installations](https://github.com/jordwalke/esy/issues/12) we want to create a set of wrapping scripts that appear to be binaries `binaryName` but where:

- `binaryName` is in the global npm modules path.
- `binaryName` is a wrapping script that`cd`s into the right directory then calls `esy binaryName` to call the *real* binary.

When you call `binaryName` from the CLI, it gets picked up by the global npm install paths - not `esy`. When the `binaryName` wrapper script runs `esy binaryName`, `esy` should be pure and scrub away the npm `PATH`. Why?

1. We don't want `esy binaryName` to invoke the wrapper script itself! (could that infinitely loop?)
2. If `binaryName` (the actual binary, not wrapper script) were to call `anotherBinaryName`, we don't want *it* to see the wrapper scripts, because that would cause loading of environment twice.

So as it is the current implementation of `esy` works really well for these wrapper scripts, but if we make `esy command` more "relaxed" this approach will no longer work and the wrapper scripts must be updated to use `esypure command`.
